const constants = {
    LIST_LOADING: "LIST_LOADING" ,
    LIST_SUCCESS: "LIST_SUCCESS" ,
    LIST_FAILED: "LIST_FAILED" ,

    ITEM_LIST_LOADING: "ITEM_LIST_LOADING",
    ITEM_LIST_SUCCESS:"ITEM_LIST_SUCCESS",
    ITEM_LIST_FAILED: "ITEM_LIST_FAILED",

    PRICE_RANGE: "PRICE_RANGE",
    STAR_RAINGS: "STAR_RAINGS",

}


export default constants;